name: charity_game
description: Platform designed for building habit of donating to charities

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.12.0+1
  get_it: 2.0.1
  rxdart: 0.22.1+1
  shimmer: 1.0.0
  carousel_slider: 1.3.0
  flutter_spinkit: 4.0.0
  auto_size_text: 2.1.0
  expandable: 3.0.0+1
  percent_indicator: 2.1.1+1
  intl: 0.15.8
  font_awesome_flutter: 8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/placeholder.jpg

  fonts:
    - family: iconmoon
      fonts:
        - asset: assets/icons/icomoon.ttf